Part17. Подготовка приложения и деплой (#36)
* Feat: поменять адаптер базы данных

Вместо mysql теперь postgresql. В файле postgresql.md
содержатся ошибки, возникшие при установке postgresql
и решения на них.

* Fix: renamed postgresql.md

* Fix: renamed postgresql.md

* Fix: улучшить читаемость текста

* Fix: оформить как код последний кусок

* Fix: добавить описание последней проблемы

Смена кодировки для таблиц (по-умолчанию?)

* Fix: улучшить форматирование

* Fix: вставить обязательный пароль при создании пользователя

* Feat: добавить настройки для onrender.com

Один файл исполняемый скрипт для ассетов
Второй - описание деплоя

* Fix: добавить гем faraday-retry

Возможно, что из-за него не получалось развернуть сайт..

* Feat: добавить ссылку на базу данных

* Fix: поменять имя базы на guru_development

* Fix: удалил файлы и создал снова

* Fix: поменять databaseName на mysite

* Feat: add 'npm init'

* Fix: добавить скрипт build:css в package.json для yarn

Хотя render жаловался на `bun run build:css`
я взял кусок из моего работающего скрипта для пустого приложения
для yarn.

* Fix: убрать висячую запятую в конце скрипта build:css

* Fix: добавить все скрипты из работающего сайта

Ошибка была такой:
No packages! Deleted empty lockfile
$ bun run build:css:compile && yarn build:css:prefix
error: Script not found "build:css:compile"
error: script "build:css" exited with code 1
bin/rails aborted!

* Fix: заменить application.bootstrap.scss на application.scss

Ошибка:
$ sass ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules
Error reading app/assets/stylesheets/application.bootstrap.scss: Cannot open file.
error: script "build:css:compile" exited with code 66
error: script "build:css" exited with code 66
bin/rails aborted!

* Fix: убрать строку с комментарием

error: JSON does not support comments
    at /opt/render/project/src/package.json:12:5

* Feat: установить boostrap

npm install bootstrap

* Fix: заменить путь к bootstrap

* Fix: добавить закрывающую кавычку

* Fix: вернуть нормальный application.scss

без него сайт локально не запускается

* Fix: убрать cssbundling,

И заменить @import "bootstrap" на @import "_bootstrap"
app/assets/stylesheets/application.scss

* Fix: добавить миграции

в render-build.sh добавить строку
bundle exec rails db:migrate
для исправления ошибки

I, [2024-05-02T14:00:24.641368 #106]  INFO -- : [a525f9b8-f1ca-42c6-b53c-2f3fbbd4e8a1] Completed 500 Internal Server Error in 280ms (ActiveRecord: 63.5ms | Allocations: 7383)
E, [2024-05-02T14:00:24.641889 #106] ERROR -- : [a525f9b8-f1ca-42c6-b53c-2f3fbbd4e8a1]
[a525f9b8-f1ca-42c6-b53c-2f3fbbd4e8a1] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 10:  WHERE a.attrelid = '"users"'::regclass
                             ^
):

* Fix: изменить сайт вместо localhost - сайт на рендере

Для исправления этой ошибки
[33bbf26b-eed1-420f-8baf-62ccfcb30450] ActionView::Template::Error
(Missing host to link to! Please provide the :host parameter,
set default_url_options[:host], or set :only_path to true):

* Fix: добавить конфигурацию action-mailer

* Fix: добавить пропущенную запятую

в конфигурации action_mailer была пропущена запятая

* Feat: сохранить все настройки smtp в credentials

* Fix: изменить настройки почты

* Fix: заменить дефолтные настройки почты в development

заменить дефолтные настройки почты в окружениии development
для проверки работы почты БЕЗ ГЕМА letter_opener

* Fix: EOFError in Devise::RegistrationsController#create

Исправить эту ошибку указанием названия почты вместо тестового

* Feat: сделать указанного пользователя админом

* Fix: заменить smtp-настройки хешем

* Fix: убрать лишние комментарии для action_mailer

* Fix: обновить схему БД

* Feat: добавить категории для тестов

* Fix: устранить ошибку при отправке письма

при завершении теста неверно указано имя почтового ящика
в свойства application_mailer

* Fix: поместить имя пользователя почты в credentials

* Fix: удалить пару пользоватлей в db:seed

* Feat: добавить ссылку обратной связи

* Feat: реализовать обратную связь

Добавлены модель, миграции, контроллер, локализация

* Feat: показывать ошибки валидации обратной связи

и добавить локализацию

* Feat: отправить по почте сообщение отправителю обратной связи

* Fix: исправить ошибку с вводом имени и фамилии

* Fix: разрешить в параметрах сохранять имя и фамилию пользователя

* Feat: отправить письмо с фидбеком администратору

* Feat: убрать гем dotenv

поместить токен для создания gist в credentials

* Fix: удалить директорию node_modules

---------

Co-authored-by: slydevruby <slydevruby@zohomail.com>